version: '2'
services:
    sugah-app:
        image: sugah
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sugah-mysql:3306/sugah?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sugah-mysql:
        extends:
            file: mysql.yml
            service: sugah-mysql
